<%@ Page Language="c#" Inherits="myob_files" AutoEventWireup="true" CodeFile="myob_files.aspx.cs"
    EnableViewState="false" %>

<!DOCTYPE html>
<html>
<head runat="server">
    <title>MYOB files</title>
</head>
<body>
    <form id="frmMain" method="post" runat="server">
        <div style=""
            class="ListContainer">
            <asp:TreeView ID="tvDirectoryList" runat="server" AutoGenerateDataBindings="false" ImageSet="XPFileExplorer" ExpandDepth="1" Width="100%">
                <Nodes>
                    <asp:TreeNode Text="MYOB files"></asp:TreeNode>
                </Nodes>
            </asp:TreeView>
        </div>
    </form>
</body>
</html>