<%@ Page Language="c#" Inherits="payroll_pdf_files" AutoEventWireup="true" CodeFile="payroll_pdf_files.aspx.cs"
    EnableViewState="false" %>

<!DOCTYPE html>
<html>
<head runat="server">
    <title>Payroll PDF System</title>
</head>
<body>
    <form id="frmMain" method="post" runat="server">
        <div class='container-fluid'>
            <div class="row">
                <div class="col-sm-4" >
                    <bw:bwCheckBox Label="Show all" ID="chkShowAll" runat="server" AutoPostBack="true" />
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-4" style="height: 80vh;">
                    <asp:TreeView ID="tvDirectoryList" runat="server" AutoGenerateDataBindings="false" ImageSet="XPFileExplorer" ExpandDepth="1" Width="100%">
                        <Nodes>
                            <asp:TreeNode Text="PayrollTimeSheets"></asp:TreeNode>
                        </Nodes>
                    </asp:TreeView>
                </div>
                <div class="col-sm-4" style="height: 80vh;">
                    <asp:TreeView ID="tvTimesheet2" runat="server" AutoGenerateDataBindings="false" ImageSet="XPFileExplorer" ExpandDepth="1" Width="100%">
                        <Nodes>
                            <asp:TreeNode Text="PayrollTimeSheets2"></asp:TreeNode>
                        </Nodes>
                    </asp:TreeView>
                </div>
            </div>
        </div>
    </form>
</body>
</html>
